# SPDX-FileCopyrightText: 2017-2021 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

header.pageNumber=Sivu 
header.decisionNumber=Päätöksen numero
text.decision.sentDate=Päätöspvm {0}

decision.details.child.prefix=Lapsellenne
decision.details.child={0} {1} (s. {2})
decision.details.date=<strong>on tehty päätös Petäjäveden kunnan varhaiskasvatukseen ajalle</strong>

decision.placement.unit=Varhaiskasvatusyksikkö varhaiskasvatuksen alkaessa

decision.daycareTime=Varhaiskasvatusaika
decision.fullTime=Kokoaikainen
decision.partTime=Osa-aikainen

decision.sentDate=Päätös- ja lähetyspäivä

decision.approver.prefix=Päätöksentekijä
decision.approver.additionalInfo=(allekirjoitettu sähköisesti)
decision.approver.title=Päiväkodin johtaja
decision.approver.unit=Varhaiskasvatus

decision.approver.address=Suutarintie 4, 41900 Petäjävesi, PETÄJÄVEDEN KUNTA
decision.approver.phoneNumber=Puhelinnumero: 040 700 1879
decision.approver.email.heading=Sähköposti:
decision.approver.email.email=varhaiskasvatus@petajavesi.fi

decision.inform.guardians=Tiedoksi: Huoltajat

decision.unit.name=Varhaiskasvatusyksikkö:
decision.child.name=Lapsen nimi:
decision.unitsupervisor=Varhaiskasvatusyksikön johtaja

decision.acceptance.child.name=Lapsen nimi:
decision.acceptance.unit.name=Varhaiskasvatusyksikkö:

decision.acceptance.furtherInstructions=<p>Päätöksessä ilmoitetun paikan <strong>vastaanottamis- tai kieltäytymisilmoitus on toimitettava välittömästi, viimeistään kahden viikon kuluessa</strong> tämän ilmoituksen saamisesta. Paikan voi käydä hyväksymässä/hylkäämässä sähköisesti osoitteessa <a href="https://evaka.petajavesi.fi" rel="noreferrer">evaka.petajavesi.fi</a> (vaatii kirjautumisen).</p>
