name: Pet - Push release images to ECR

on:
  workflow_dispatch:
    inputs:
      sourceRelease:
        description: 'Select release from https://github.com/espoon-voltti/evaka/releases or use "latest"'
        required: true
        type: string
        default: 'latest'
      pushToDev:
        description: 'Push images to the development ECR'
        required: true
        type: boolean
        default: true
      pushToTest:
          description: 'Push images to the test ECR'
          required: true
          type: boolean
          default: true

jobs:
  pull_tag_and_push:
    name: "Pull, tag and push images"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Resolve release commit SHA
        env:
          GH_TOKEN: ${{ github.token }}
          REPO_NAME: evaka
          REPO_OWNER: espoon-voltti
        run: |
          # Resolve commit SHA for the selected or the latest release
          if [ "${{ inputs.sourceRelease }}" == "latest" ]; then
            echo "Resolving latest release and its commit SHA.."
            latest_release=$(gh api graphql -f query='{repository(owner:"espoon-voltti", name:"evaka"){latestRelease{tagName}}}' | jq -r '.data.repository.latestRelease.tagName')
            echo "Latest release: \"$latest_release\""
            commit_sha=$(gh api graphql -f query='{repository(owner:"espoon-voltti", name:"evaka"){latestRelease{tagCommit {oid}}}}' | jq -r '.data.repository.latestRelease.tagCommit.oid')
          else
            echo "Resolving commit SHA for the specific release: \"${{ inputs.sourceRelease }}\".."
            commit_sha=$(gh api graphql -f query='{repository(owner:"espoon-voltti", name:"evaka"){release(tagName: "v20250418"){tagCommit{oid}}}}' | jq -r '.data.repository.release.tagCommit.oid')
          fi
          echo "Commit SHA: \"$commit_sha\""
          echo "COMMIT_SHA=$commit_sha" >> $GITHUB_OUTPUT
          echo "FRONTEND_SRC_IMG=ghcr.io/espoon-voltti/evaka/frontend-common:$commit_sha" >> $GITHUB_ENV
          echo "APIGW_SRC_IMG=ghcr.io/espoon-voltti/evaka/api-gateway:$commit_sha" >> $GITHUB_ENV
          echo "SERVICE_SRC_IMG=ghcr.io/espoon-voltti/evaka/service:$commit_sha" >> $GITHUB_ENV

      - name: Pull images from the source eVaka repo
        run: |
          # Pull images from the source eVaka repo
          echo "Pulling images from the source eVaka repo using tag: ${{ inputs.sourceCommit }}"
          echo -n "evaka/frontend-common image: "
          docker pull --quiet ${{ env.FRONTEND_SRC_IMG }}
          echo -n "evaka/api-gateway image: "
          docker pull --quiet ${{ env.APIGW_SRC_IMG }}
          echo -n "evaka-service image: "
          docker pull --quiet ${{ env.SERVICE_SRC_IMG }}
          
      - name: Configure AWS Credentials (Dev)
        if: inputs.pushToDev
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          unset-current-credentials: true
          role-to-assume: ${{ secrets.ECR_ROLE_ARN_DEV }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 900 # Min is 900
          retry-max-attempts: 3
      - name: Login to ECR (Dev)
        if: inputs.pushToDev
        uses: aws-actions/amazon-ecr-login@v2
      - name: Tag and push images (Dev)
        if: inputs.pushToDev
        env:
          FRONTEND_DST_IMG: "${{ secrets.ECR_HOST_DEV }}/evaka/frontend-common:${{ inputs.sourceRelease }}"
          APIGW_DST_IMG: "${{ secrets.ECR_HOST_DEV }}/evaka/api-gateway:${{ inputs.sourceRelease }}"
          SERVICE_DST_IMG: "${{ secrets.ECR_HOST_DEV }}/evaka/service:${{ inputs.sourceRelease }}"
        run: |
          # Tag and push images (Dev)
          echo "Tagging Dev images"
          docker tag ${{ env.FRONTEND_SRC_IMG }} ${{ env.FRONTEND_DST_IMG }}
          docker tag ${{ env.APIGW_SRC_IMG }} ${{ env.APIGW_DST_IMG }}
          docker tag ${{ env.SERVICE_SRC_IMG }} ${{ env.SERVICE_DST_IMG }}
          echo "Pushing images to Dev ECR"
          echo -n "evaka/frontend-common image: "
          docker push --quiet ${{ env.FRONTEND_DST_IMG }}
          echo -n "evaka/api-gateway image: "
          docker push --quiet ${{ env.APIGW_DST_IMG }}
          echo -n "evaka-service image: "
          docker push --quiet ${{ env.SERVICE_DST_IMG }}

      - name: Configure AWS Credentials (Test)
        if: inputs.pushToTest
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          unset-current-credentials: true
          role-to-assume: ${{ secrets.ECR_ROLE_ARN_TEST }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 900 # Min is 900
          retry-max-attempts: 3
      - name: Login to ECR (Test)
        if: inputs.pushToTest
        uses: aws-actions/amazon-ecr-login@v2
      - name: Tag and push images (Test)
        if: inputs.pushToTest
        env:
          FRONTEND_DST_IMG: "${{ secrets.ECR_HOST_TEST }}/evaka/frontend-common:${{ inputs.sourceRelease }}"
          APIGW_DST_IMG: "${{ secrets.ECR_HOST_TEST }}/evaka/api-gateway:${{ inputs.sourceRelease }}"
          SERVICE_DST_IMG: "${{ secrets.ECR_HOST_TEST }}/evaka/service:${{ inputs.sourceRelease }}"
        run: |
          # Tag and push images (Test)
          echo "Tagging Test images"
          docker tag ${{ env.FRONTEND_SRC_IMG }} ${{ env.FRONTEND_DST_IMG }}
          docker tag ${{ env.APIGW_SRC_IMG }} ${{ env.APIGW_DST_IMG }}
          docker tag ${{ env.SERVICE_SRC_IMG }} ${{ env.SERVICE_DST_IMG }}
          echo "Pushing images to Test ECR"
          echo -n "evaka/frontend-common image: "
          docker push --quiet ${{ env.FRONTEND_DST_IMG }}
          echo -n "evaka/api-gateway image: "
          docker push --quiet ${{ env.APIGW_DST_IMG }}
          echo -n "evaka-service image: "
          docker push --quiet ${{ env.SERVICE_DST_IMG }}
