name: Pet - Build and deploy

# Required GitHub Actions Environment Variables:
# - AWS_REGION, e.g. eu-north-1

# Required GitHub Actions Secrets:
# - GH_ACTIONS_ROLE_ARN, e.g. arn:aws:iam::123456789012:role/evaka-github-actions-role-dev
# - ECR_HOST, e.g. 123456789012.dkr.ecr.eu-north-1.amazonaws.com


on:
  push:
    branches:
      - test
      - prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REF: ${{ github.ref_name }}
  ECS_CLUSTER_NAME: evaka-${{ github.ref_name }}


jobs:

  cache-bust:
    runs-on: ubuntu-latest
    steps:
      - name: "Cache bust"
        id: cache-bust
        run: echo "cache-bust=$(date '+%Y-%V')" >> "$GITHUB_OUTPUT"
    outputs:
      cache-bust: ${{ steps.cache-bust.outputs.cache-bust }}

  frontend-common:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: read
    needs:
      - cache-bust
    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          unset-current-credentials: true
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 1800 # Min is 900
          retry-max-attempts: 3

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate Docker metadata
        id: metadata
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.ECR_HOST }}/evaka/frontend-common
          tags: |
            type=raw,value=${{ env.REF }}
            type=sha,format=short

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          cache-from: type=gha,scope=frontend-common
          cache-to: type=gha,mode=max,scope=frontend-common
          build-args:
            CACHE_BUST=${{ needs.cache-bust.outputs.cache-bust }}
            build=${{ github.run_number }}
            commit=${{ github.sha }}
            ICONS=free
            EVAKA_CUSTOMIZATIONS=petajavesi
          build-contexts: customizations=frontend/src/lib-customizations/petajavesi
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true

      - name: Update SSM Parameter Store
        id: update-ssm-parameter-store
        run: aws ssm put-parameter --name evaka_frontend_image --value ${{ fromJSON(steps.metadata.outputs.json).tags[1] }} --overwrite
      
      - name: Update Amazon ECS task definition
        id: render-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-family: evaka-frontend
          container-name: evaka-frontend
          image: ${{ fromJSON(steps.metadata.outputs.json).tags[1] }}
          
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-container.outputs.task-definition }}
          service: evaka-frontend
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
      

  api-gateway:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: read
    needs:
      - cache-bust
    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          unset-current-credentials: true
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 1800 # Min is 900
          retry-max-attempts: 3

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate Docker metadata
        id: metadata
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.ECR_HOST }}/evaka/api-gateway
          tags: |
            type=raw,value=${{ env.REF }}
            type=sha,format=short

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./apigw
          cache-from: type=gha,scope=apigw
          cache-to: type=gha,mode=max,scope=apigw
          build-args: 
            CACHE_BUST=${{ needs.cache-bust.outputs.cache-bust }}
            build=${{ github.run_number }}
            commit=${{ github.sha }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true

      - name: Update SSM Parameter Store
        id: update-ssm-parameter-store
        run: aws ssm put-parameter --name evaka_apigw_image --value ${{ fromJSON(steps.metadata.outputs.json).tags[1] }} --overwrite

      - name: Update Amazon ECS task definition
        id: render-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-family: evaka-apigw
          container-name: evaka-apigw
          image: ${{ fromJSON(steps.metadata.outputs.json).tags[1] }}
          
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-container.outputs.task-definition }}
          service: evaka-apigw
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true

  service:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: read
    needs:
      - cache-bust
    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          unset-current-credentials: true
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 1800 # Min is 900
          retry-max-attempts: 3

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate Docker metadata
        id: metadata
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.ECR_HOST }}/evaka/service
          tags: |
            type=raw,value=${{ env.REF }}
            type=sha,format=short

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: service/Dockerfile
          cache-from: type=gha,scope=service
          cache-to: type=gha,mode=max,scope=service
          build-args: 
            CACHE_BUST=${{ needs.cache-bust.outputs.cache-bust }}
            build=${{ github.run_number }}
            commit=${{ github.sha }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true

      - name: Update SSM Parameter Store
        id: update-ssm-parameter-store
        run: aws ssm put-parameter --name evaka_service_image --value ${{ fromJSON(steps.metadata.outputs.json).tags[1] }} --overwrite

      - name: Update Amazon ECS task definition
        id: render-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-family: evaka-service
          container-name: evaka-service
          image: ${{ fromJSON(steps.metadata.outputs.json).tags[1] }}
          
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-container.outputs.task-definition }}
          service: evaka-service
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true

  test-db:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'test' }}
    environment:
      name: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: read
    needs:
      - cache-bust
    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          unset-current-credentials: true
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 1800 # Min is 900
          retry-max-attempts: 3

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate Docker metadata
        id: metadata
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.ECR_HOST }}/test-db
          tags: |
            type=raw,value=${{ env.REF }}
            type=sha,format=short

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./compose/db
          cache-from: type=gha,scope=test-db
          cache-to: type=gha,mode=max,scope=test-db
          build-args: 
            CACHE_BUST=${{ needs.cache-bust.outputs.cache-bust }}
            build=${{ github.run_number }}
            commit=${{ github.sha }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true

      # - name: Update SSM Parameter Store
      #   id: update-ssm-parameter-store
      #   run: aws ssm put-parameter --name evaka_test_db_image --value ${{ fromJSON(steps.metadata.outputs.json).tags[1] }} --overwrite

      # - name: Update Amazon ECS task definition
      #   id: render-container
      #   uses: aws-actions/amazon-ecs-render-task-definition@v1
      #   with:
      #     task-definition-family: test-db
      #     container-name: test-db
      #     image: ${{ fromJSON(steps.metadata.outputs.json).tags[1] }}
          
      # - name: Deploy Amazon ECS task definition
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      #   with:
      #     task-definition: ${{ steps.render-container.outputs.task-definition }}
      #     service: test-db
      #     cluster: ${{ env.ECS_CLUSTER_NAME }}
      #     wait-for-service-stability: true

  dummy-idp:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'test' }}
    environment:
      name: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: read
    needs:
      - cache-bust
    steps:
      
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          unset-current-credentials: true
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 1800 # Min is 900
          retry-max-attempts: 3

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate Docker metadata
        id: metadata
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.ECR_HOST }}/dummy-idp
          tags: |
            type=raw,value=${{ env.REF }}
            type=sha,format=short

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./dummy-idp
          cache-from: type=gha,scope=dummy-idp
          cache-to: type=gha,mode=max,scope=dummy-idp
          build-args: 
            CACHE_BUST=${{ needs.cache-bust.outputs.cache-bust }}
            build=${{ github.run_number }}
            commit=${{ github.sha }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true

      - name: Update SSM Parameter Store
        id: update-ssm-parameter-store
        run: aws ssm put-parameter --name dummy_idp_image --value ${{ fromJSON(steps.metadata.outputs.json).tags[1] }} --overwrite

      - name: Update Amazon ECS task definition
        id: render-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-family: dummy-idp
          container-name: dummy-idp
          image: ${{ fromJSON(steps.metadata.outputs.json).tags[1] }}
          
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-container.outputs.task-definition }}
          service: dummy-idp
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true